"""Generate docs/mcp_tools.md (and docs/mcp_tools.json) from the live MCP server definition."""

from __future__ import annotations

import asyncio
import inspect
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from clausewatch.mcp_server import mcp  # noqa: E402


def _type(p: dict, defs: dict) -> str:
    if "$ref" in p:
        return p["$ref"].split("/")[-1]
    if "anyOf" in p:
        return " | ".join(_type(x, defs) for x in p["anyOf"])
    if p.get("type") == "array":
        return f"list[{_type(p['items'], defs)}]"
    if "enum" in p:
        return " | ".join(f'"{e}"' for e in p["enum"])
    return p.get("type", "any")


def _fields(schema: dict, defs: dict) -> list[str]:
    req = set(schema.get("required", []))
    rows = []
    for name, p in schema.get("properties", {}).items():
        default = f" (default `{p['default']}`)" if "default" in p else ""
        desc = p.get("description", "")
        typ = _type(p, defs).replace("|", "\\|")
        desc = desc.replace("|", "\\|")
        rows.append(f"| `{name}` | `{typ}` | {'yes' if name in req else 'no'}{default} | {desc} |")
    return rows


def main() -> None:
    tools = asyncio.run(mcp.list_tools())
    dumped = [t.model_dump(exclude_none=True, by_alias=True) for t in tools]
    out = ["# ClauseWatch MCP tools", "",
           "Generated by `python scripts/dump_mcp_schemas.py`. Full JSON schemas: [`mcp_tools.json`](mcp_tools.json).", ""]
    for d in dumped:
        out += [f"## `{d['name']}`", "", inspect.cleandoc(d.get("description", "")), "", "**Input**", ""]
        rows = _fields(d["inputSchema"], {})
        out += (["| Field | Type | Required | Description |", "|---|---|---|---|", *rows] if rows else ["_none_"])
        osch = d.get("outputSchema")
        if osch:
            defs = osch.get("$defs", {})
            out += ["", "**Output**", ""]
            if set(osch.get("properties", {})) == {"result"}:  # list / wrapped returns
                out.append(f"`{_type(osch['properties']['result'], defs)}`")
            else:
                out += ["| Field | Type | Required | Description |", "|---|---|---|---|", *_fields(osch, defs)]
            for name, sub in defs.items():
                out += ["", f"<details><summary><code>{name}</code></summary>", "",
                        "| Field | Type | Required | Description |", "|---|---|---|---|", *_fields(sub, defs),
                        "", "</details>"]
        out.append("")
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "mcp_tools.md").write_text("\n".join(out))
    (docs / "mcp_tools.json").write_text(json.dumps(dumped, indent=1))
    print(f"wrote {len(dumped)} tools")


if __name__ == "__main__":
    main()
